.Dd May 21, 2019
.Dt RECURSE_CENTER 1
.Os
.Sh NAME
.Nm recurse_center
.Nd a self-directed, community-driven educational retreat for people who want to get better at programming.
.Sh SYNOPSIS
.Nm
.Op Fl mhf
.Op Fl d Ar date
.Sh DESCRIPTION
The
.Nm
is a self-directed, community-driven educational retreat for programmers in New York City. RC believes people learn best when they take control of their own education and are free to explore what they're interested in. RC is heavily influenced by unschooling.
.Sh OPTIONS
The following options are available:
.Bl -tag -width XXrXXXrecursiveX
.It Fl m , -mini
This option selects a 1-week mini batch..
.It Fl h , -half
This option selects a 6-week batch.
.It Fl f , -full
This option selects a full 12-week batch
.It Fl d , -date
This option specifies the batch date.
.El
.Sh SEE ALSO
.Xr y_combinator 1 ,
.Xr etsy 1 ,
.Xr bradfield 1 
.Sh HISTORY
The
.Nm
was initially founded in the Summer of 2010 as Hackruiter, an engineering recruiting company, using seed money from Y Combinator. The idea quickly arose of trying to transform recruiting for start-ups by running a retreat as part of the process, with the goal of helping clients become better programmers.
It officially opened its doors as Hacker School in New York in July, 2011, obliquely anticipating the coding bootcamp movement that arose in the mid-2010s. Hacker School came to wide public attention in mid-2012, when it partnered with the e-commerce company Etsy to offer Hacker Grants in support of female developers.
In 2015 Hacker School was renamed the Recurse Center.
.Sh AUTHORS
This implementation of
.Nm
was written by
.An David Albert, Nick Bergson-Shilcock, and Sonali Sridhar .
